server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/syncfit-msa/Config-Repo
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          search-paths:
            - user-service
            - track-service
            - recommendation-service
            - wishlist-service
            - auth-service
            - youtube-service
            - api-gateway
            - service-discovery
    bus:
      enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,health,info
